### ISSUE TITLE
(android) feature request: next track inside zip file

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [vitamin-caig/zxtune#2176]
﻿hi

I use zxtune on android to play vgz files inside a ZIP file.
If I click the zip file, zxtune opens it and shows all vgz files inside.

If I click a vgz file I can play it successfully.

The problem with zip files is: the player does not go automatically to the next vgz file in the zip file.
It plays the selected one and then stops.

would it be possible to automatically play all vgz files in a zip file? So if you select one to play, the player will play the next track automatically untill there are no more files left in the zip file?

thx in advance!

**Comment by vitamin-caig** [comment]
Hello!

Unfortunately, it's not impossible in general. If you'll browse that archive you'll get idea why - all the vgz files are treated as a isolated folders and ZXTune does not move to another folder after playback is finished in current.
But there's some solutions for you:
1) do not store your vgz files inside archive - it's useless. vgz is just gzipped vgm, so you'll not get any additional compression
2) store vgm files in archive instead of vgz
3) add your archive to playlist (long tap to select, then click to appeared plus button at the right top corner). You'll also get an ability to play tracks in random order
4) (not obvious, so not recommended and subject to change) start playback with some track located before your archive in browser then navigate to the next track
