### ISSUE TITLE
feature request: vgmstream

### ISSUE THREAD

**Issue by froggestspirit** [vitamin-caig/zxtune#2182]
would it be possible to add vgmstream as a plugin? this would add support for most streamed game music. if not, is there a code example for adding new plugins?

**Comment by vitamin-caig** [comment]
No. Any. Binary. Plugins. Ever.

As for source-level integration check out sources at src/core/plugins. But vgmstream is not intended to be integrated with ease. Moreover, it's not crossplatform.

**Comment by wyatt8740** [comment]
@vitamin-caig can you elaborate on 'not crossplatform?'

I do agree that the integration part is pretty awful, but I'm able to emit signed 16-bit little endian samples over stdout, pipe them into ffmpeg and push the audio to my speakers from there on a BSD system (as well as from Linux). So even though I do feel like a second-class citizen it seems ostensibly somewhat portable from where I'm standing.

I'm sure you have better understanding of the situation than I do, though, since I just found out about vgmstream today.

**Comment by vitamin-caig** [comment]
> I do agree that the integration part is pretty awful
That's the main issue. Moreover, some of the formats support is implemented via external dynamic library - this is unacceptable.

> but I'm able to emit signed 16-bit little endian samples over stdout, pipe them into ffmpeg and push the audio to my speakers from there on a BSD system with -f oss /dev/dsp (as well as ALSA in desktop Linux with -f alsa <sink name>).
Pipe is not the suitable way to integrate code to monolithic binary (as zxtune is). In order to integrate new thirdparty library I have to step-by-step:
- analyze the sources for entrypoints
- analyze the sources for specific requirements (no file IO, thread safety or thread hostility at least - that means no any global or static variables except once initialized)
- try to build library in zxtune build environment (usually problems with buildflags and includes)
- possibly, modify sources to exclude redundant parts (trying to keep changes as small as possible)
- research signatures for each new format dropping way too fuzzy ones 
- comprehensive test for all the test tracks available to ensure no crashes

I don't this is impossible, but I have to prioritize due to lack of spare time(

**Comment by wyatt8740** [comment]
Thanks for the quick response.

If I feel up to it I might make an attempt at some of this at some point, but I don't know if I really want to, either. :)

I've done some of these sorts of things before - I once ported an OSS direct-access program to use ALSA by rewriting some C code, for instance ([sexypsf](https://github.com/wyatt8740/sexypsf/)). But it was not very fun, and that code still has some problems (needs `-fcommon`, for instance - it's a pretty old program).

**Comment by vitamin-caig** [comment]
I've made some experimental integration - looks successful:) Not all the formats will be supported at the first iteration (due to models differences), but nevertheless.

**Comment by vitamin-caig** [comment]
Limited vgmstream support is implemented starting from b5010.
