### ISSUE TITLE
[Feedback / Reply] Playlists Are Not Intuitive

### ISSUE THREAD

**Issue by JoLiKMC** [vitamin-caig/zxtune#2239]
Hello and sorry it took me so long to reply.  Been kinda busy.

So, I left a review for this on the Google Play Store commenting about how saving Playlists wasn't very intuitive — specifically, "Saving Playlists isn't entirely intuitive, and it's annoying that it has to rescan all the files when loading from a playlist."  I was then asked the following by the developer:

> What the problems do you have with playlists saving?

Since I can't reply there, here I am.

The way I make playlists using the AndroidOS version of _ZXTune_ is as follows:

0. Download and open the app. (Of course!)
1. Go to the in-app Browser and give it permission to browse your files, then refresh.
2. Browse to the files or folder you want to add to a playlist.  Tap-and-hold, then hit the Add to Playlist button. (Three lines and a plus mark.)
3. Go to the Playlist section and press the Save button. (Looks like a 5.25" floppy disk.)  Tap to save to a persistent location. (First time only.)  The playlist is now saved.

The problem I'm having is that switching between multiple playlists is kind of a pain in the butt.  You can find them in your "Playlists" folder easily enough, but if you tap on the playlist file, it just opens the file as a list of files — like another folder — rather than offering to add to or replace your current playlist.  Once again, you have to press-and-hold the file in order to have it open in your playlist properly.  Doing so will add the playlist's content to your current playlist without removing anything that may already be there.  In that regard, it's no different than pressing-and-holding on the folder(s) I want, rendering them… kind of pointless?  Especially since you can't access them from the Playlist menu.

I'm not trying to badmouth the product, itself.  It's a very good chiptunes player, and the fact that it can download and play random tunes from _The Mod Archive_ is absolutely *amazing*!  I just think playlist management could be a little less clunky under Android.  That's all.

Hopefully, I explained this well enough.  Cheers!

**Comment by vitamin-caig** [comment]
Hello!

First of all, I want to thank you for such a detailed feedback! I do appreciate users who apply efforts and give details rather than moronic 'nothing worked, 1 star, solve this puzzle dumbass':(

As for playlists. I agree that current model is not clear (since it's not final yet). Just think that stored playlists are just sets of references - that's why they are treated as a folders, not only while browsing but also while scanning (i.e. you may select folder with stored playlists only and add it to app's playlist). This also:
- covers general case 'add stored playlist to current one'
- makes sure all added tracks are available and playable (though this requires additional time)
- all required network resources are prefetched and cached

I'm planning to implement multiple playlists support - there should be dropdown list at the top of playlist panel and new 'add to new playlist' button.  Also there should be playlist deduplication button.
This should cover all your needs I guess:)

**Comment by JoLiKMC** [comment]
Ah, that makes sense.  I look forward to future developments, in that case!

I've edited my Play Store review to reflect this new information.  Thank you very much!

(I'm closing this as "Resolved" since it's being worked on, but definitely open this back up if you think it'll be useful to other users!)
